TEXT_OUTPUT_LIMIT = 20
MAX_LENGTH_TEXT = 50
LENGTH_INPUT_FIELD = 256
MAX_LENGTH_ROLE = 10
MAX_LENGTH_CONFIRMATION_CODE = 6
MAX_LENGTH_USERNAME = 150
MAX_LENGTH_NAME = 150
FORBIDDEN_USERNAMES = ("me",)