# Generated by Django 5.1.3 on 2024-12-14 15:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("favorites", "0001_initial"),
        ("recipes", "0003_alter_recipe_options_remove_recipe_is_favorited_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="favorite",
            unique_together={("user", "recipe")},
        ),
    ]
