# Generated by Django 5.1.3 on 2024-12-22 12:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Cooking time must be at least 10 minute."
                    ),
                    django.core.validators.MaxValueValidator(
                        32000, message="Cooking time must not exceed 32000 minutes."
                    ),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="amount",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Cooking time must be at least 10 minute."
                    ),
                    django.core.validators.MaxValueValidator(
                        32000, message="Cooking time must not exceed 32000 minutes."
                    ),
                ]
            ),
        ),
    ]
