# Generated by Django 5.1.3 on 2024-12-14 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_alter_ingredient_options_recipe_is_favorited_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipe",
            options={"ordering": ["name"]},
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="is_favorited",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="is_in_shopping_cart",
        ),
    ]
