# Generated by Django 5.1.3 on 2024-12-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="avatar",
        ),
        migrations.AddField(
            model_name="user",
            name="avtar",
            field=models.ImageField(blank=True, null=True, upload_to="users/"),
        ),
    ]
