# Generated by Django 5.1.3 on 2024-12-04 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_user_avatar_user_avtar"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="avtar",
            new_name="avatar",
        ),
    ]
